name: "On Main Push"
description: "Fill this out..."
inputs:
    github-token: # id of input
        description: "Github Token"
        required: true
# outputs:
#     time: # id of output
#         description: "The time we greeted you"
runs:
    using: "node20"
    main: "index.mjs"
