name: Pull Request Closed

on:
    pull_request:
        types: [closed]

jobs:
    stuff:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Use Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
                  cache: "npm"
            - run: npm ci
            - run: npm run esbuild

            - name: JS Test
              uses: ./.github/workflows/actions/pull-request-closed
