name: Release-Test

on:
    release:
        types: [released]

jobs:
    stuff:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: get-npm-version pre
              id: package-version-pre
              uses: martinbeentjes/npm-get-version-action@main

            - name: Version Pre
              run: echo ${{ steps.package-version-pre.outputs.current-version}}

            - name: Use Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"
            - run: npm i
            - run: npm run esbuild

            - name: JS Test
              uses: ./.github/workflows/actions/js-test

            - name: Package
              id: package
              run: npm run package

            - name: Upload Release Assets
              run: gh release upload v${{ steps.package-version-pre.outputs.current-version}} ./*.vsix
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
